name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        Please describe your idea in detail.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area would this feature affect?
      options:
        - Backend API
        - Frontend Mobile App
        - Database
        - Authentication
        - AI Features
        - Dating Features
        - Chart Calculations
        - DevOps/Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: I also considered...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this feature?
      placeholder: |
        - Improved user experience
        - Better performance
        - etc.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocking users)
        - High (important for many users)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples
      placeholder: Attach images or links here

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical details or constraints to consider?
      placeholder: This would require...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all requested information
          required: true
        - label: I am willing to help implement this feature
          required: false
