-- Add ai_generated_at field to charts table
-- This field tracks when the chart interpretation was generated by AI
-- Used for rate limiting (1 AI generation per day)

ALTER TABLE "public"."charts"
ADD COLUMN IF NOT EXISTS "ai_generated_at" TIMESTAMP WITH TIME ZONE;

-- Add index for efficient querying of recent AI generations
CREATE INDEX IF NOT EXISTS "charts_ai_generated_at_idx"
ON "public"."charts"("ai_generated_at");

-- Add comment to explain the field
COMMENT ON COLUMN "public"."charts"."ai_generated_at" IS 'Timestamp of last AI interpretation generation. Used for rate limiting (max 1 per day).';
